# "It took the night to believe"

language: c

before_script:
  - cmake --help
  - cmake $CMAKE_OPTIONS $CMAKE_GENERATOR .

env:
  - CTEST_OUTPUT_ON_FAILURE=1

addons:
  apt:
    packages:
    - cmake
    - libpopt-dev
    - doxygen
    - ninja-build
  homebrew:
    packages:
      - popt
    update: true

script:
  - make check

matrix:
  include:
    - os: windows

    - os: osx
      compiler: clang

    - os: linux
      compiler: gcc

    - os: linux
      compiler: clang

    - os: linux
      compiler: clang
      env: CMAKE_GENERATOR="-G Ninja"
      script: ninja check doc

    - os: linux
      compiler: gcc
      env: CMAKE_OPTIONS="-D BUILD_SHARED_LIBS=OFF"

    - os: linux
      compiler: gcc
      env: CMAKE_OPTIONS="-D BUILD_RDIFF=OFF"

# vim: shiftwidth=2 expandtab
